### ISSUE TITLE
ETHERPAD - boot takes too much time and sometimes timeouts in Heroku

### ISSUE THREAD

**Issue by tiblu** [citizenos/etherpad-lite-heroku#5]
**Overview**

It takes very long for Etherpad to be ready to serve clients, sometimes it even timeouts. We have raised the Heroku boot timeout, but ideally we would like Etherpad to boot faster.

```
» 2 Feb 2017 21:41:40.269  151 <45>1 2017-02-02T19:41:39.591196+00:00 host heroku web.1 - Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
» 2 Feb 2017 21:41:40.347  89 <45>1 2017-02-02T19:41:39.591196+00:00 host heroku web.1 - Stopping process with SIGKILL
» 2 Feb 2017 21:41:40.567  90 <45>1 2017-02-02T19:41:39.877887+00:00 host heroku web.1 - Process exited with status 137
» 2 Feb 2017 21:41:40.570  98 <45>1 2017-02-02T19:41:39.885426+00:00 host heroku web.1 - State changed from starting to crashed
» 2 Feb 2017 22:01:39.773  315 <158>1 2017-02-02T20:01:38.633197+00:00 host heroku router - at=error code=H10 desc="App crashed" method=GET path="/socket.io/?EIO=3&transport=polling&t=1486065697617-5" host=p.citizenos.com request_id=3b50efef-c183-4f3d-b25a-93146c772dbb fwd="217.71.47.179,141.101.80.59" dyno= connect= service= status=503 bytes= Fatal
```

**Heroku plz?**

* Wasn't Heroku supposed to make sure new instance booted before letting traffic on the new one?
For me it looks like it let traffic on while the app was not up:

```
» 2 Feb 2017 22:01:43.672  315 <158>1 2017-02-02T20:01:42.455765+00:00 host heroku router - at=error code=H10 desc="App crashed" method=GET path="/socket.io/?EIO=3&transport=polling&t=1486065701618-6" host=p.citizenos.com request_id=09470387-5713-4178-8fc3-bb3c20a368d4 fwd="xxx" dyno= connect= service= status=503 bytes= Fatal
```

**Possible reasons**

* NPM install takes too long, alot of dependencies to install.

**Related issues**

* https://github.com/citizenos/etherpad-lite-heroku/issues/4

**NOTE!** Preboot (https://devcenter.heroku.com/articles/preboot) is probably NOT a solution, more information on this - https://github.com/citizenos/etherpad-lite-heroku/issues/4

**TODO**

- [x] Investigate where the time is spent and if we can do anything to help it. If need be, make a PR to Etherpad. - **Biggest problem is not EP boot time, biggest problem is our code aroud `start.js`. See "Conclusions"**
- [x] EP is supposed to NOT let traffic on the new instance before new is up, but there seems to be downtime on deploy. - **To my understanding the timetime is because we cannot use preboot (https://devcenter.heroku.com/articles/preboot), which would spin up a new instance BEFORE shutting down the old. We CANNOT use preboot for EP because that does not support horizontal scaling due to UeberDB writing to instance memory and form time to time flushing to DB.**

**Comment by loorm** [comment]
Triage 18: timebox dev time for investigation to 8 hours.

**Comment by tiblu** [comment]
**Progress**

- [ ] Check that cacheDirectories is set correctly so that NPM install would take less time - https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

**Comment by tiblu** [comment]
Task was timeboxed and ran out of time. 
Most of the time was spent on figuring out what plugins we use, can we boost the install by publishing them to NPM. Which is somewhat true, but not significant. See https://github.com/citizenos/etherpad-lite-heroku/issues/5#issuecomment-601178266

**Comment by tiblu** [comment]
**Q&A with Heroku CS**

> Is there a way to persist data between dynos? Like the build cache (https://devcenter.heroku.com/articles/nodejs-support#cache-behavior), but not at build time. So let's say new dyno is created, it would get a directory from existing dyno?

Dynos are lightweight, completely isolated environment so there's no way to get the directory from the existing dyno. You can set up a Redis cache to persist data between dynos but I don't think you can use Redis in your use case as you want to cache packages so I'm afraid that you can't achieve this.


> If I understand correctly then at build there is no way to acces environment variables of the app? It kinda makes sense as the build environment and dyno are totally different things.
WRONG. 

Environment variables are available during build time - https://devcenter.heroku.com/articles/nodejs-support#environment-variables

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
